version: "3"
services:
  task:
    environment:
      PORT: ${PORT:-8080} # Default value should match the default at index.ts
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PROTOCOL: ${MONGODB_PROTOCOL}
      MONGODB_PORT: ${MONGODB_PORT}
      REDIS_URL: ${REDIS_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      LOG_LEVEL: ${LOG_LEVEL}
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT-8080}:${PORT-8080} # Default value should match the default at index.ts
    volumes:
      - ./src:/usr/app/src
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27017:${MONGODB_PORT}
    volumes:
      - mongodb_data_container:/data/db
      - mongodb_config_container:/data/configdb
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongodb_data_container:
  mongodb_config_container:
